#**Data, Variabel and Regular Expresion**

## Jenis Data dalam Statistik

### 1. Data Numerik
Pembagian Pertama
* Diskret(discrete)
  - Ada karena dihitung (counted)
  - Tidak memilki koma (integer)
  - Contoh : lemparan 2 buah dadu (2,3,4,5,6,7,8,9,10,11,12)
* Kontinu(continous)
  - Ada karena diukur (measured)
  - Memiliki koma dan nilai tak terbatas (infinite)
  - Contoh : Jarak, tinggi badan, berat badan

Pembagian Kedua
* Interval
  - Tidak memiliki arti angka nol (no true zero)
  - Bisa bernilai negatif dan bisa dijumlahkan/dikurangi
  - Contoh : Suhu(Celsius) ,Waktu (Jam 2, Jam 3), IQ
* Rasio 
  - Memiliki arti angka nol (true zero)
  - Tidak bernilai negatif dan bisa dijumlahkan, kurang, kali, bagi
  - Contoh : Jarak, Kadar Obat, Durasi

### 2. Data Kategori (Nominal)
- Lebih bersifat kualitatif
- Bagian dari beberapa kelompok

  Contoh : Data Ras, Data Warna Rambut
- Angka numerik dari data kategori ini tidak memiliki nilai matematis

### 3. Data Rangking (Ordinal)
- Campuran data numerik dan data kategori
- Angka yang dimilki oleh data ordinal memilki arti matematis
- Nilai yang dimungkinkan dalam data ordinal ini biasanya memiliki rentang tertentu

  Contoh : Rating Kuesioner, Rating Aplikasi

##**Konsep dan Tipe Data**

Tipe Data adalah jenis data yang mampu ditangani oleh suatu bahasa pemrograman pada computer.

### 1. Number

  Tipe Numerik di Python terdiri dari int, float dan *complex*

1. Integer : Menyatakan Bilangan Bulat
2. Float : Menyatakan Bilangan yang mempunyai koma atau bilangan desimal
3. Kompleks : Menyatakan pasangan angka real dan imajiner


In [1]:
a = 20
print(a, "bertipe", type(a))

20 bertipe <class 'int'>


In [ ]:
b = 20.0
print(b, "bertipe", type(b))

20.0 bertipe <class 'float'>


In [ ]:
c = 1+3j
print(c, "bertipe", type(c))

(1+3j) bertipe <class 'complex'>


### 2. String

  String adalah urutan dari karakter unicode yang dideklarasikan dengan petik tinggal atau ganda. String lebih dari 1 baris daat ditandai dengan tiga petik tunggal atau ganda

In [ ]:
a = "Ini adalah string baris tunggal"
print(a)
print(a, "bertipe", type(a))

Ini adalah string baris tunggal
Ini adalah string baris tunggal bertipe <class 'str'>


In [ ]:
b = '''Ini adalah string
yang memiliki baris pertama
dan selanjutnya baris kedua'''
print(b)

Ini adalah string
yang memiliki baris pertama
dan selanjutnya baris kedua


### 3. Boolean

  Tipe data bool atau Boolean merupakan turunan dari bilangan bulat (integer atau int) yang hanya punya dua nilai konstanta: True dan False.

In [ ]:
a = True
print(a,"bertipe", type(a))

True bertipe <class 'bool'>


## Struktur Data

Struktur Data adalah cara penyimpanan dan pengorganisasian data-data pada memori computer maupu file secara efektif sehingga dapat diguakan secara efisien, termasuk operasi-operasi didalamnya

### 1. List

  List adalah jenis kumpulan data terurut (ordered sequence), dan merupakan salah satu variabel yang sering digunakan pada Python. Serupa, namun tak sama dengan array pada bahasa pemrograman lainnya. Bedanya, elemen List pada Python tidak harus memiliki tipe data yang sama. Mendeklarasikan List cukup mudah dengan kurung siku dan elemen yang dipisahkan dengan koma. 

In [ ]:
a = [1, 2.2, 'python']
print(a,"bertipe", type(a))

[1, 2.2, 'python'] bertipe <class 'list'>


### 2. Tuple

  Tuple adalah jenis dari list yang tidak dapat diubah elemennya. Umumnya tuple digunakan untuk data yang bersifat sekali tulis, dan dapat dieksekusi lebih cepat. Tuple didefinisikan dengan kurung dan elemen yang dipisahkan dengan koma.

In [ ]:
a = (5,'program', 1+3j)
print(a,"bertipe", type(a))

(5, 'program', (1+3j)) bertipe <class 'tuple'>


### 3. Set

  Set adalah kumpulan item bersifat unik dan tanpa urutan (unordered collection). Didefinisikan dengan kurawal dan elemennya dipisahkan dengan koma. Pada Set kita dapat melakukan union dan intersection, sekaligus otomatis melakukan penghapusan data duplikat.

In [ ]:
a = {1,2,3}
print(a,"bertipe", type(a))

{1, 2, 3} bertipe <class 'set'>


In [ ]:
a = {1.3,True,'Saya'}
print(a,"bertipe", type(a))

{'Saya', 1.3, True} bertipe <class 'set'>


### 4. Dictionary

  Dictionary pada Python adalah kumpulan pasangan kunci-nilai (pair of key-value) yang bersifat tidak berurutan. Dictionary dapat digunakan untuk menyimpan data kecil hingga besar. Untuk mengakses datanya, kita harus mengetahui kuncinya (key). Pada Python, dictionary didefinisikan dengan kurawal dan tambahan definisi berikut:
  1. Setiap elemen pair key-value dipisahkan dengan koma (,).
  2. Key dan Value dipisahkan dengan titik dua (:).
  3. Key dan Value dapat berupa tipe variabel/obyek apapun.

In [ ]:
a = {1:'value','key':2}
print(a,"bertype", type(a))

{1: 'value', 'key': 2} bertype <class 'dict'>


##**Konversi Data**

Kita dapat melakukan konversi tipe data bawaan dengan menggunakan fungsi konversi tipe bawaan (standard type) misalnya: int(), float(), str(), dll.

In [ ]:
# Konversi dari Integer ke Float
a = 5
print(float(a))

5.0


In [ ]:
# Konversi dari  Float ke Integer
a = 10.6
print(int(a))

10


In [ ]:
# Konversi dari String ke Float
a = '2.5'
print(float(a))

2.5


In [ ]:
# Konversi dari Integer ke String
a = 25
print(str(a))

25


In [ ]:
# Konversi dari List ke Set
a = [1,2,3]
print(set(a))

{1, 2, 3}


In [ ]:
# Konversi dari Set ke Tuple
a = {5,6,7}
print(tuple(a))

(5, 6, 7)


In [ ]:
# Konversi dari String ke List
a = 'hello'
print(list(a))

['h', 'e', 'l', 'l', 'o']


In [ ]:
# Konversi dari List ke Dictionary
a = [[1,2],[3,4]]
print(dict(a))

{1: 2, 3: 4}


##Vektor, Matriks dan Array

### Vektor

Vektor adalah besaran yang memiliki arah dan juga besaran, terutama sebagai penentu posisi suatu titik dalam ruang relatif terhadap titik lainnya. Vektor sangat penting dalam Machine Learning karena tidak hanya mendeskripsikan besaran tetapi juga arah . Kita dapat membuat vektor di NumPy dengan potongan kode berikut:

In [ ]:
import numpy as np

vektor_baris = np.array([1,2,3])
print(vektor_baris)

[1 2 3]


Kita juga dapat membuat vektor kolom sebagai:

In [ ]:
import numpy as np

vektor_kolom = np.array([[1],[2],[3]])
print(vektor_kolom)

[[1]
 [2]
 [3]]


Dot Product di Vektor

`np.dot ()`

Contoh :


In [ ]:
a = np.array ( [ 3 , 5 , 6 ] )
b = np.array ( [ 23 , 15 , 1 ] )

np.dot ( a, b )

150

Mencari rata-rata   
`np.mean ()`

Contoh :

In [ ]:
vektor = [1,2,3,4,5,6,7,8,9]
np.mean ( vektor )

5.0

Mencari Varians 

`np.var ()`

Contoh :


In [ ]:
vektor = [1,2,3,4,5,6,7,8,9]
np.var ( vektor )

6.666666666666667

Mencari Standar Deviasi

`np.std ()`

Contoh :


In [ ]:
vektor = [1,2,3,4,5,6,7,8,9]
np.std ( vektor )

2.581988897471611

### Matriks

Matriks dapat secara sederhana dipahami sebagai larik dua dimensi. Kita bisa membuat matriks dengan NumPy dengan membuat array multi dimensi:

In [ ]:
matriks = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matriks)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Operasi Transpose pada matriks

`matrix.T`

Contoh :


In [ ]:
matriks = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
transpos_matriks = matriks.T
print(transpos_matriks)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


Penjumlahan pada Matriks

`np.add ()`

Contoh :


In [ ]:
matriks = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
penjumlahan_matriks = np.add ( matriks, matriks )
print(penjumlahan_matriks)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


Pengurangan pada Matriks

`np.subtract ()`

Contoh :


In [ ]:
matriks = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
pengurangan_matriks = np.subtract ( matriks, matriks )
print(pengurangan_matriks)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


###**Array** 

Array merupakan sekumpulan variabel yang memiliki tipe data yang sama dan mampu menyimpan beberapa nilai dalam satu variabel. Array merupakan tipe data terstruktur dalam pemrograman, array memungkinkan untuk menyimpan data maupun referensi objek dalam jumlah banyak dan terindeks. Sehingga sejumlah variabel dapat menggunakan nama yang sama.

Contoh mendefinisikan suatu array:

In [ ]:
import numpy as np

angka = np.array([ 1, 2, 3 ,4])
nama = np.array(["Dono", "Kasino", "indro"])
print(nama)
print(angka)

['Dono' 'Kasino' 'indro']
[1 2 3 4]


In [ ]:
angka = np.array([ 1, 2, 3 ,4 ])
print(type(angka))

<class 'numpy.ndarray'>


Operasi Elemen pada Array

Contoh : 

In [ ]:
import numpy as np
angka = np.array([ 1, 2, 3 ,4 ])

# Operasi Penjumlahan 
penjumlahan = angka + angka
print(penjumlahan)

# Operasi Pengurangan 
pengurangan = angka - angka
print(pengurangan)

# Operasi Perkalian
perkalian = angka * angka
print(perkalian)

# Operasi Pembagian 
pembagian = angka / angka
print(pembagian)

# Operasi Pangkat
pangkat = angka ** angka
print(pangkat)

[2 4 6 8]
[0 0 0 0]
[ 1  4  9 16]
[1. 1. 1. 1.]
[  1   4  27 256]


Menghitung Dimensi

Untuk mengetahui jumlah dimensi pada data menggunakan fungsi 
`ndim`

Contoh :

In [ ]:
a = np.array([1,2,3])
print("array tersebut berdimensi", a.ndim)

array tersebut berdimensi 1


Jenis Jenis Array

1. Array satu dimensi merupakan sebuah variabel yang menyimpan sekumpulan data yang memiliki tipe sama dan elemen yang akan diakses melalui satu index atau subskrip.        
    Contoh: `nama_array[jumlah_elemen];`

2. Array dua dimensi merupakan sebuah variabel yang menyimpan sekupmulan data yang memiliki tipe sama dan elemen yang akan diakses memalui dua indeks atau sub skrip yaitu index baris dan index kolom. 
    Contoh: `nama_array[jumlah_elemen_baris][jumlah_elemen_kolom];`     

Struktur Data

* Index : kembalikan indeks item pertama dalam array yang mana nilainya “x”. `array.index(x)`

Contoh :

* Append : menambahkan sebuah item baru pada akhir array `array.append(x)`

In [ ]:
array = [1,2,3,4]
array.append(5)
print(array)

[1, 2, 3, 4, 5]


* Insert : memasukkan item baru ke dalam “x” sebelum “i” `array.insert(i,x)`

In [ ]:
array = [1,2,3,4]
array.insert(1,3)
print(array)

[1, 3, 2, 3, 4]


* Remove : menghapus item bernilai “x” dalam array. `array.remove(x)`

In [ ]:
array = [1,2,3,4]
array.remove(1)
print(array)

[2, 3, 4]


* Pop : menghapus item dalam posisi tertentu dalam indeks kemudian mengembalikannya. `array.pop([i])`

* Count : kembalikan pada jumlah item “x” di dalam array. `array.count(x)`

* Reverse : membalikan urutan item dalam array sehingga indeks dari setiap item berubah secara terbalik. `array.reverse()`

* Extend : menambahkan item tertentu dalam akhir array `array.extend('')`

In [ ]:
array = [1,2,3,4]
array.extend('STIS')
print(array)

[1, 2, 3, 4, 'S', 'T', 'I', 'S']


* Sort : mengurutkan item dalam array. `array.sort()`

In [ ]:
array = [10,6,7,1,9,5]
array.sort()
print(array)

[1, 5, 6, 7, 9, 10]


* Len : mengembalikan nilai berupa jumlah item di dalam sebuah array. `len()`

  * Del : menghapus item dalam array `del L[i]`

In [ ]:
array = [1,2,3,4]
del array[1]
print(array)

[1, 3, 4]


Array dan Vektor Serupa tapi Tak Sama

Secara umum, array satu dimensi dengan vector jika dilihat secara sepintas terlihat sangat mirip dan susah untuk dibedakan sehingga tidak jarang banyak orang yang menyebut bahwa vector adalah array satu dimensi, sedangkan array dua dimensi adalah matrix. Ternyata yang membedakan antara vector dan array adalah array dapat dilakukan proses transpose, sedangkan vector tidak dapat di-transpose.


Array Juga Berbeda dengan List

Berbeda dengan array dan vector yang berada di bawah package numpy, untuk list sendiri berada di bawah package pandas karena bisa memuat data selain angka, misalnya saja string, boolean, dll. List pada Python bersifat mutable yang artinya elemen nya bisa dimodifikasi. Perbedaan yang sangat menonjol antara list dengan array dan vector adalah list berisi kumpulan data dimana data tersebut memiliki tipe data yang sama, misalnya angka (number), string, dll.

## **List**



### Pengertian List
List adalah jenis kumpulan data terurut (ordered sequence), dan merupakan salah satu variabel yang sering digunakan pada Python. Serupa, namun tak sama dengan array pada bahasa pemrograman lainnya. Bedanya, elemen List pada Python tidak harus memiliki tipe data yang sama. Mendeklarasikan List cukup mudah dengan kurung siku dan elemen yang dipisahkan dengan koma. 
Setiap data di dalamnya dapat diakses dengan indeks yang dimulai dari 0.

Python mengenal slicing operator [] yang dapat melakukan ekstraksi sebuah item atau beberapa item yang berada dalam range tertentu pada tipe data urutan (sequences), misalnya list, string dan tuple. Beberapa tipe urutan juga mendukung "extended slicing" dengan parameter ketiga berupa "step".

* `x[0]` artinya mengambil elemen paling awal, dengan index 0 dari List x.

* `x[5]` artinya mengambil elemen dengan index 5 dari List x.

* `x[-1]` artinya mengambil elemen dengan index paling belakang ke-1 dari List x.

* `x[3:5]` artinya membuat list dari anggota elemen List x dengan index 3 hingga sebelum index 5 (tidak termasuk elemen dengan index 5, dalam hal ini hanya index 3-4).

* `x[:5]` artinya membuat list dari anggota elemen List x paling awal hingga sebelum index 5 (tidak termasuk elemen dengan index 5, dalam hal ini hanya index 0-4).

* `x[-3:]` artinya membuat list dari anggota elemen List x mulai index ke-3 dari belakang hingga paling belakang.

* `x[1:7:2]` artinya membuat list dari anggota elemen List x dengan index 1 hingga sebelum index 7, dengan "step" 2 (dalam hal ini hanya index 1, 3, 5).

Contoh : 

In [ ]:
x = [5,10,15,20,50,30,35,40]
print(x[5])
print(x[-1])
print(x[3:5])
print(x[:5])
print(x[-3:])
print(x[1:7:2])

30
40
[20, 50]
[5, 10, 15, 20, 50]
[30, 35, 40]
[10, 20, 30]


In [ ]:
# Melakukan pengubahan
array1 = [1,2,3]
array1[2]=4
print (x)

[5, 10, 15, 20, 50, 30, 35, 40]


In [ ]:
# Melakukan pengubahan dan penambahan
x = [1,2,3]
x[2]=4
x.append(5)
print(x)

[1, 2, 4, 5]


Untuk menghapus item pada list, gunakan fungsi del. Ingat bahwa Indeks Python dimulai dari 0:

In [ ]:
binatang = ['kucing', 'rusa', 'badak', 'gajah']
del binatang[2]
print(binatang)

['kucing', 'rusa', 'gajah']


### Slicing pada String

Karena string mirip dengan list, maka slicing operator [ ]  juga dapat digunakan pada string untuk mengambil isinya atau bahkan substring. Sebuah string utuh bersifat mutable (bisa diubah), namun elemennya bersifat immutable (tidak bisa diubah).

In [ ]:
s = "Hello World!"
print(s[4])  	#ambil karakter kelima dari string s
print(s[6:11]) 		#ambil karakter ketujuh hingga sebelas dari string s


o
World


In [ ]:
s = "Hello World!"
s = "Halo Dunia!"	#ubah isi string s menjadi "Halo Dunia!", seharusnya berhasil karena mutable
print (s)

Halo Dunia!


In [ ]:
s[5]="d" 		      #ubah karakter keenam dari string s menjadi "d", seharusnya gagal karena immutable
print (s)

TypeError: ignored

## Series dan Data Frame



### 1. Series

Series merupakan struktur data dasar dalam Pandas. Series bisa juga diibaratkan sebagai array satu dimensi seperti halnya yang ada pada numpy array, hanya bedanya mempunyai index dan kita dapat mengontrol index dari setiap elemen tersebut.
Struktur data yang bisa ditampung berupa integer, float, dan juga string. Series juga mendukung operasi vektor. Secara definisi, Series tidak dapat mempunyai kolom ganda, untuk masalah ini bisa menggunakan struktur data frame.

In [ ]:
import pandas as pd
import numpy as np

data = np.array([2,4,6,8,10])
nilai_series = pd.Series(data, index=['a','b','c','d','e'])
print(nilai_series)
print(type(nilai_series))

a     2
b     4
c     6
d     8
e    10
dtype: int64
<class 'pandas.core.series.Series'>


### 2. Data Frame

Data frame merupakan tabel/data tabular dengan array dua dimensi yaitu baris dan kolom. Struktur data ini merupakan cara paling standar untuk menyimpan data. Setiap kolom pada Data Frame merupakan objek dari Series, dan baris terdiri dari elemen yang ada pada Series. Contoh berikut menunjukkan pembuatan Data Frame yang sederhana:

Contoh Data Frame yang nilainya di buat random :

In [ ]:
import pandas as pd
import numpy as np

np.random.seed(100)
dataku = pd.DataFrame(np.random.randn(5,5),["A","B","C","D","E"],["Satu","Dua","Tiga","Empat","Lima"])
print(dataku)
type(dataku)

       Satu       Dua      Tiga     Empat      Lima
A -1.749765  0.342680  1.153036 -0.252436  0.981321
B  0.514219  0.221180 -1.070043 -0.189496  0.255001
C -0.458027  0.435163 -0.583595  0.816847  0.672721
D -0.104411 -0.531280  1.029733 -0.438136 -1.118318
E  1.618982  1.541605 -0.251879 -0.842436  0.184519


pandas.core.frame.DataFrame

In [ ]:
# Menghitung banyak baris dan kolom

dataku.shape  # Baris dimulai dengan index 0, sedangkan Kolom dimulai dengan index 1

(5, 5)

In [ ]:
# Memilih data

hasil = dataku[dataku["Tiga"]>0]
print(hasil)

       Satu      Dua      Tiga     Empat      Lima
A -1.749765  0.34268  1.153036 -0.252436  0.981321
D -0.104411 -0.53128  1.029733 -0.438136 -1.118318


Contoh Data Frame :

In [ ]:
import pandas as pd
import numpy as np

data1 = {"Negara": ["Indonesia", "Jepang", "India", "China", "Amerika Serikat"],
        "Ibu Kota": ["Jakarta", "Tokyo", "New Delhi", "Beijing", "Washington, D.C."],
        "Luas": [1905, 377972, 3287, 9597, 9834],
        "Populasi": [264, 143, 1252, 1357, 5298] }

dataku = pd.DataFrame(data1)

print(dataku)

            Negara          Ibu Kota    Luas  Populasi
0        Indonesia           Jakarta    1905       264
1           Jepang             Tokyo  377972       143
2            India         New Delhi    3287      1252
3            China           Beijing    9597      1357
4  Amerika Serikat  Washington, D.C.    9834      5298


In [ ]:
import pandas as pd
import numpy as np

data1 = {"Negara": ["Indonesia", "Jepang", "India", "China", "Amerika Serikat"],
        "Ibu Kota": ["Jakarta", "Tokyo", "New Delhi", "Beijing", "Washington, D.C."],
        "Luas": [1905, 377972, 3287, 9597, 9834],
        "Populasi": [264, 143, 1252, 1357, 5298] }

dataku = pd.DataFrame(data1)

#Menambahkan kolom baru
dataku['Mata Uang'] = ["Rupiah","Yen","Rupee","Renminbi","Dolar"] 

print(dataku)

            Negara          Ibu Kota    Luas  Populasi Mata Uang
0        Indonesia           Jakarta    1905       264    Rupiah
1           Jepang             Tokyo  377972       143       Yen
2            India         New Delhi    3287      1252     Rupee
3            China           Beijing    9597      1357  Renminbi
4  Amerika Serikat  Washington, D.C.    9834      5298     Dolar


In [ ]:
import pandas as pd
import numpy as np

data1 = {"Negara": ["Indonesia", "Jepang", "India", "China", "Amerika Serikat"],
        "Ibu Kota": ["Jakarta", "Tokyo", "New Delhi", "Beijing", "Washington, D.C."],
        "Luas": [1905, 377972, 3287, 9597, 9834],
        "Populasi": [264, 143, 1252, 1357, 5298] }

dataku = pd.DataFrame(data1)

# Menambahkan kolom baru
dataku['Mata Uang'] = ["Rupiah","Yen","Rupee","Renminbi","Dolar"] 

# Menghapus suatu kolom
dataku.drop("Luas",axis=1,inplace=True)

print(dataku)

            Negara          Ibu Kota  Populasi Mata Uang
0        Indonesia           Jakarta       264    Rupiah
1           Jepang             Tokyo       143       Yen
2            India         New Delhi      1252     Rupee
3            China           Beijing      1357  Renminbi
4  Amerika Serikat  Washington, D.C.      5298     Dolar


In [ ]:
import pandas as pd
import numpy as np

data1 = {"Negara": ["Indonesia", "Jepang", "India", "China", "Amerika Serikat"],
        "Ibu Kota": ["Jakarta", "Tokyo", "New Delhi", "Beijing", "Washington, D.C."],
        "Luas": [1905, 377972, 3287, 9597, 9834],
        "Populasi": [264, 143, 1252, 1357, 5298], }

dataku = pd.DataFrame(data1)

# Menambahkan kolom baru
dataku['Mata Uang'] = ["Rupiah","Yen","Rupee","Renminbi","Dolar"] 

# Menghapus suatu kolom
dataku.drop("Luas",axis=1,inplace=True)

# Mengapus suatu baris
dataku.drop(4,axis=0,inplace=True)

print(dataku)

      Negara   Ibu Kota  Populasi Mata Uang
0  Indonesia    Jakarta       264    Rupiah
1     Jepang      Tokyo       143       Yen
2      India  New Delhi      1252     Rupee
3      China    Beijing      1357  Renminbi


## Indexing Array dan Data Frame

### 1. Indexing Array

Indeks pada suatu array dimulai pada indeks ke-0. Untuk mengakses element pada array, kita menggunakan indeks sebagai alamat elemen pada array.


In [ ]:
array1 = np.array([5,10,15,20,50,30,35,40])
print(array1[5])
print(array1[-1])
print(array1[3:5])
print(array1[:5])
print(array1[-3:])
print(array1[1:7:2])

30
40
[20 50]
[ 5 10 15 20 50]
[30 35 40]
[10 20 30]


In [ ]:
array2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array2)
print("Elemen yang terletak pada baris 3 kolom 1 yaitu",array2[2,0])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Elemen yang terletak pada baris 3 kolom 1 yaitu 7


### 2. Indexing Data Frame

In [ ]:
import pandas as pd
import numpy as np

data1 = {"Negara": ["Indonesia", "Jepang", "India", "China", "Amerika Serikat"],
        "Ibu Kota": ["Jakarta", "Tokyo", "New Delhi", "Beijing", "Washington, D.C."],
        "Luas": [1905, 377972, 3287, 9597, 9834],
        "Populasi": [264, 143, 1252, 1357, 5298] }

dataku = pd.DataFrame(data1)

print(dataku)

            Negara          Ibu Kota    Luas  Populasi
0        Indonesia           Jakarta    1905       264
1           Jepang             Tokyo  377972       143
2            India         New Delhi    3287      1252
3            China           Beijing    9597      1357
4  Amerika Serikat  Washington, D.C.    9834      5298


In [ ]:
df = dataku.set_index(["Negara"])
print(df)

                         Ibu Kota    Luas  Populasi
Negara                                             
Indonesia                 Jakarta    1905       264
Jepang                      Tokyo  377972       143
India                   New Delhi    3287      1252
China                     Beijing    9597      1357
Amerika Serikat  Washington, D.C.    9834      5298


In [ ]:
print("Luas Wilayah Indonesia adalah",df['Luas']["Indonesia"],"km persegi")

Luas Wilayah Indonesia adalah 1905 km persegi


## Variabel

Variabel adalah lokasi memori yang dicadangkan untuk menyimpan nilai-nilai. Ini berarti bahwa ketika Anda membuat sebuah variabel Anda memesan beberapa ruang di memori. Variabel menyimpan data yang dilakukan selama program dieksekusi, yang nantinya isi dari variabel tersebut dapat diubah oleh operasi - operasi tertentu pada program yang menggunakan variabel.

Variabel dapat menyimpan berbagai macam tipe data. Di dalam pemrograman Python, variabel mempunyai sifat yang dinamis, artinya variabel Python tidak perlu didekralasikan tipe data tertentu dan variabel Python dapat diubah saat program dijalankan.

Penulisan variabel Python sendiri juga memiliki aturan tertentu, yaitu :

1. Karakter pertama harus berupa huruf atau garis bawah
2. Karakter selanjutnya dapat berupa huruf, garis bawahatau angka
3. Karakter pada nama variabel bersifat sensitif (case-sensitif). Artinya huruf kecil dan huruf besar dibedakan. Sebagai contoh, variabel namaDepan dan namadepan adalah variabel yang berbeda.

Untuk mulai membuat variabel di Python caranya sangat mudah, Anda cukup menuliskan variabel lalu mengisinya dengan suatu nilai dengan cara menambahkan tanda sama dengan = diikuti dengan nilai yang ingin dimasukan.

## Regular Expresion

Regular Expresion, sering disebut pola, adalah ekspresi yang digunakan untuk menentukan sekumpulan string yang diperlukan untuk tujuan tertentu.

### 1. Character Classes
* Character Set : Cocokkan semua karakter di set.

  Contoh : `[ABC]`

* Negated Set : Cocokkan semua karakter yang tidak ada di set

  Contoh : `[^ABC]`

* Range : Mencocokkan karakter yang memiliki kode karakter di antara dua karakter yang ditentukan, termasuk.

  Contoh : `[A-Z]`

* Dot : Mencocokkan karakter apa pun kecuali penggalan baris. Setara dengan `[^\ n\r]`

  Contoh : `.`

* Match Any : Alternatifnya adalah [^], tetapi tidak didukung di semua browser.

  Contoh : `[\s\S]`

* Word : Cocok dengan semua karakter kata (alfanumerik & garis bawah). Hanya cocok dengan karakter ascii rendah (tidak ada karakter beraksen atau non-romawi). Setara dengan `[A-Za-z0-9_]`

  Contoh : `\w`

* Not Word : Cocok dengan semua karakter yang bukan karakter kata (alfanumerik dan garis bawah). Setara dengan `[^ A-Za-z0-9_]`

  Contoh : `\W`

* Digit : Cocok dengan karakter digit apa pun (0-9). Setara dengan `[0-9]`.

  Contoh : `/d`

* Not Digit : Cocok dengan semua karakter yang bukan karakter digit (0-9). Setara dengan `[^ 0-9]`.

  Contoh : `/D`

* Whitespace : Cocok dengan semua karakter spasi (spasi, tab, jeda baris)

  Contoh : `\s`

* Not Whitespace : Mencocokkan semua karakter yang bukan karakter spasi (spasi, tab, jeda baris).

  Contoh : `\S`

* Unicode Category : Cocok dengan karakter dalam kategori unicode yang ditentukan. 
  
  Contoh : `\p{Ll}` akan cocok dengan semua huruf kecil.

* Not Unicode Category : Cocok dengan semua karakter yang tidak ada dalam kategori unicode yang ditentukan.

  Contoh : `\P{Ll}`
* Unicode Script : Cocok dengan semua karakter dalam skrip unicode yang ditentukan. 

  Contoh : `\p{Arab}` akan mencocokkan karakter dalam skrip Arab.
  
* Not Unicode Script : Cocok dengan semua karakter yang tidak ada dalam skrip unicode yang ditentukan.

  Contoh : `\P{Arab}`
  

In [ ]:
# Contoh Character Set

import re
txt = """
Yesterday, I was driving my car without a driving licence. The traffic police stopped me and asked me for my 
license. I told them that I forgot my licence at home. 
"""
pattern = re.compile("licen[cs]e")
pattern.findall(txt)

['licence', 'license', 'licence']

In [ ]:
# Contoh Range

txt = """
The first season of Indian Premiere League (IPL) was played in 2008. 
The second season was played in 2009 in South Africa. 
Last season was played in 2018 and won by Chennai Super Kings (CSK).
CSK won the title in 2010 and 2011 as well.
Mumbai Indians (MI) has also won the title 3 times in 2013, 2015 and 2017
"""
pattern = re.compile("[1-9][0-9][0-9][0-9]")
pattern.findall(txt)

['2008', '2009', '2018', '2010', '2011', '2013', '2015', '2017']

In [ ]:
# Contoh Negated Set

txt = "Descent Bootcamp"
pattern = re.compile("[^aeiou]")
pattern.findall(txt)

['D', 's', 'c', 'n', 't', ' ', 'B', 't', 'c', 'm', 'p']

In [ ]:
# Contoh Character Set

txt = "Descent Bootcamp"
pattern = re.compile("[aeiou]")
pattern.findall(txt)

['e', 'e', 'o', 'o', 'a']

In [ ]:
# Contoh Whitespace

txt = "Hari ini."
re.findall("[\s]", txt)

[' ']

In [ ]:
# Contoh Not Whitespace

txt = "Hari ini."
re.findall("[\S]", txt)

['H', 'a', 'r', 'i', 'i', 'n', 'i', '.']

In [ ]:
# Contoh Word

txt = "Hari ini ."
re.findall("[\w]", txt)

['H', 'a', 'r', 'i', 'i', 'n', 'i']

In [ ]:
# Contoh Not Word

txt = "Saya mengantuk."
re.findall("\W", txt)

[' ', '.']

In [ ]:
# Contoh Digit

txt = "Saya lahir tahun 2002."
re.findall("\d", txt)

['2', '0', '0', '2']

In [ ]:
# Contoh Non Digit

txt = "Tahun 2021."
re.findall("\D", txt)

['T', 'a', 'h', 'u', 'n', ' ', '.']

### 2. Anchors
* Beginning `^` : Cocok dengan awal string, atau awal baris jika multiline flag (m) diaktifkan. Ini cocok dengan posisi, bukan karakter. `^`

  Contoh : `^\w+`

* End `$` : Cocok dengan akhir string, atau akhir baris jika multiline flag (m) diaktifkan. Ini cocok dengan posisi, bukan karakter. 

  Contoh : `\w+$`

* Word Boundary `\b`: Mencocokkan posisi batas kata antara karakter kata dan karakter atau posisi non-kata (awal / akhir string).

  Contoh : `s\b`

* Not Word Boundary `\B` : Cocok dengan posisi apa pun yang bukan merupakan batas kata. Ini cocok dengan posisi, bukan karakter.

  Contoh : `s\B`


In [ ]:
# Contoh Beginning

txt = "she sells seashells"
pattern = re.compile("^\w+")
pattern.findall(txt)

['she']

In [ ]:
# Contoh End 

txt = "she sells seashells"
pattern = re.compile("\w+$")
pattern.findall(txt)

['seashells']

In [ ]:
# Contoh Word Not Boundary

txt = "she sells seashells"
pattern = re.compile("s\B")
pattern.findall(txt)

['s', 's', 's', 's']

### 3. Escaped Characters

* Reserved Characters : Karakter berikut memiliki arti khusus, dan harus diawali dengan \ (garis miring terbalik) untuk mewakili karakter literal: `+*?^$\.[]{}()|/` 

  Contoh : `\+`

* Octal Escape : Karakter lolos oktal dalam bentuk `\000`. Nilai harus kurang dari `255 (\ 377)`.

  Contoh : `\251`

* Hexadecimal Escape : Karakter pelolosan heksadesimal dalam bentuk `\xFF`

  Contoh : `\xA9`

* Unicode Escape : Unicode lolos karakter dalam bentuk `\ uFFFF`

  Contoh : `\u00A9`

* Extended Unicode Escape : Unicode lolos karakter dalam bentuk `\u{FFFF}` Mendukung berbagai pelarian titik unicode dengan sejumlah digit hex.

* Control Character Escape : Karakter kontrol lolos dalam bentuk `\cZ`. Ini dapat berkisar dari `\cA` (SOH, kode karakter 1) hingga `\cZ` (SUB, kode karakter 26).

  Contoh : `\cI` cocok dengan TAB (kode karakter 9).

* Tab : Cocok dengan karakter TAB (kode karakter 9).

  Contoh : `\t`

* Line Feed : Cocok dengan karakter LINE FEED (kode karakter 10)

  Contoh : `\n`

* Vertical Tab : Cocok dengan karakter VERTICAL TAB (kode karakter 11).

  Contoh : `\v`

* Form Feed : Cocok dengan karakter FORM FEED (kode karakter 12)

  Contoh : `\f`

* Carriage Return : Cocok dengan karakter CARRIAGE RETURN (kode karakter 13).

  Contoh : `\r`

* Null : Matches a NULL character (char code 0).

  Contoh : `\0`



In [ ]:
# Contoh Reserved Characters

txt = "1 + 1 = 2"
pattern = re.compile("\+")
pattern.findall(txt)

['+']

### 4. Group & References

* Capturing Group : Mengelompokkan beberapa token menjadi satu dan membuat grup tangkapan untuk mengekstraksi substring atau menggunakan referensi latar.

  Contoh : `(ha)+`

* Named Capturing Group : Membuat grup penangkap yang dapat direferensikan melalui nama yang ditentukan.

  Contoh : `(?<name>ha)+`

* Numeric Refereces : Cocok dengan hasil penangkapan grup. Misalnya \ 1 cocok dengan hasil dari grup penangkapan pertama & \ 3 cocok dengan yang ketiga.

  Contoh : `(\w)a\1`

* Non-Capturing Group : Mengelompokkan beberapa token bersama-sama tanpa membuat grup tangkap.

  Contoh : `(?:ha)+`

In [ ]:
# Contoh Capturing Group

txt = "abbbbbabbbb"
pattern = re.compile("ab+")
pattern.findall(txt)

['abbbbb', 'abbbb']

In [ ]:
pattern = re.compile("(ab)+")
pattern.findall(txt)

['ab', 'ab']

### 5. Lookaround

* Positive Lookahead : Mencocokkan grup setelah ekspresi utama tanpa menyertakannya dalam hasil.

  Contoh : `\d(?=px)`

* Negative Lookahead : Menentukan grup yang tidak bisa cocok setelah ekspresi utama (jika cocok, hasilnya akan dibuang).

  Contoh : `\d(?!px)`

* Positive Lookbehind : Mencocokkan grup sebelum ekspresi utama tanpa menyertakannya dalam hasil.

  Contoh : `(?<=ABC)`

* Negative Lookbehind : Menentukan grup yang tidak bisa cocok sebelum ekspresi utama (jika cocok, hasilnya akan dibuang).

  Contoh : `(?<!ABC)`

In [ ]:
# Contoh Positive Lookahead

txt = "1pt 2px 3em 4px"
pattern = re.compile("\d(?=px)")
pattern.findall(txt)

['2', '4']

In [ ]:
# Contoh Negative Lookahead

txt = "1pt 2px 3em 4px"
pattern = re.compile("\d(?!px)")
pattern.findall(txt)

['1', '3']

### 6. Quantifiers & Alternation

* Plus `+` : Cocok dengan 1 atau lebih dari token sebelumnya.

  Contoh : `b\w+`

* Star `*`: Cocok dengan 0 atau lebih dari token sebelumnya.

  Contoh : `b\w*`

* Quantifier `{}` : Cocok dengan jumlah yang ditentukan dari token sebelumnya. {1,3} akan mencocokkan 1 dengan 3. {3} akan cocok persis dengan 3. {3,} akan cocok dengan 3 atau lebih.

  Contoh : `b\w{2,3}`

* Optional `?`: Mencocokkan 0 atau 1 dari token sebelumnya, menjadikannya opsional.

  Contoh : `colou?r`

* Lazy `?` : Membuat pembilang sebelumnya malas, menyebabkannya mencocokkan karakter sesedikit mungkin. Secara default, pembilang serakah, dan akan mencocokkan karakter sebanyak mungkin.

  Contoh : `b\w+?`

* Alternation : Bertindak seperti boolean OR. Cocok dengan ekspresi sebelum atau sesudah |.
Itu dapat beroperasi dalam kelompok, atau seluruh ekspresi. Pola akan diuji secara berurutan.

  Contoh : `b(a|e|i)d`

In [ ]:
# Contoh Plus

txt = "b be bee beer beers"
pattern = re.compile("b\w+")
pattern.findall(txt)

['be', 'bee', 'beer', 'beers']

In [ ]:
# Contoh Star

txt = "b be bee beer beers"
pattern = re.compile("b\w*")
pattern.findall(txt)

['b', 'be', 'bee', 'beer', 'beers']

In [ ]:
# Contoh Quantifier

txt = "b be bee beer beers"
pattern = re.compile("b\w{1,3}")
pattern.findall(txt)

['be', 'bee', 'beer', 'beer']

In [ ]:
# Contoh Alternation

txt = """
Siapa namamu ?
Dimana rumahmu ?
"""
pattern = re.compile("Siapa|Dimana")
pattern.findall(txt)

['Siapa', 'Dimana']

In [ ]:
# Contoh Opsional

txt = """
I have 2 dogs. One dog is 1 year old and other one is 2 years old. Both dogs are very cute! 
"""
pattern = re.compile("dogs?")
pattern.findall(txt)

['dogs', 'dog', 'dogs']

### 7. Substitution

* Match : Menyisipkan teks yang cocok.

  Contoh : `$&`

* Capture Group : Menyisipkan hasil dari grup penangkapan tertentu. 
 
  Contoh : `$3`

* Before Match :  Menyisipkan bagian dari string sumber yang mendahului pertandingan.

  Contoh : `$` `

* After Match : Menyisipkan bagian dari string sumber yang mengikuti pertandingan.

  Contoh : `$'`

* Escaped : Menyisipkan karakter tanda dolar

  Contoh : `$$`

* Escaped Characters : Demi kenyamanan, karakter yang lolos ini didukung dalam Ganti string di RegExr: \ n, \ r, \ t, \\, dan pelolosan unicode \ uFFFF. Ini mungkin berbeda di lingkungan penerapan Anda.

  Contoh : `\n`

In [ ]:
txt = "100 Kucing, 23 Anjing, 3 Kelinci"
pattern = re.compile("\d+")
pattern.sub("0", txt)

'0 Kucing, 0 Anjing, 0 Kelinci'

In [ ]:
txt = "100 Kucing"
pattern = re.compile("\D+")
pattern.sub(" Ayam ", txt)

'100 Ayam '

### 8. Flag

* Ignore Case : Membuat seluruh ekspresi peka huruf besar kecil. Misalnya, `/ aBc / i` akan cocok dengan AbC.

  Contoh : `I`

* Global Search : Pertahankan indeks dari pertandingan terakhir, yang memungkinkan pencarian berikutnya dimulai dari akhir pertandingan sebelumnya. Tanpa global flag, penelusuran selanjutnya akan mengembalikan kecocokan yang sama.

  Contoh : `G`

* Multiline : Ketika bendera multiline diaktifkan, jangkar awal dan akhir `(^ dan $)` akan cocok dengan awal dan akhir baris, bukan awal dan akhir seluruh string.
Perhatikan bahwa pola seperti `/ ^ [\ s \ S] + $ / m` dapat mengembalikan kecocokan yang menjangkau beberapa baris karena jangkar akan cocok dengan awal / akhir baris mana pun.

  Contoh : `M`

* Unicode : Jika bendera unicode diaktifkan, Anda dapat menggunakan pelolosan unicode yang diperluas dalam bentuk `\ x {FFFFF}`. Itu juga membuat pelarian lain lebih ketat, menyebabkan pelarian yang tidak dikenali (mis. `\J`) menimbulkan kesalahan.

  Contoh : `U`

* Sticky : Ekspresi tersebut hanya akan cocok dari posisi lastIndex-nya dan mengabaikan tanda global (g) jika disetel. Karena setiap penelusuran di RegExr bersifat terpisah, tanda ini tidak berdampak lebih jauh pada hasil yang ditampilkan.

  Contoh : `Y`

* Dotall : Titik (.) Akan cocok dengan karakter apapun, termasuk baris baru.

  Contoh : `S`

In [ ]:
# Contoh Ignore Case

import re

txt ="""
U.S. stock-index futures pointed
to a solidly higher open on 
Monday, indicating that major 
benchmarks were poised to rebound 
from last week’s sharp decline, 
which represented their biggest weekly drops in months.
That weakness was driven in part by 
fears over North Korea, where tensions 
with the U.S. have been escalating. 
North Korea. That issue overshadowed the state of 
the equity market, where earnings 
have been strong at a time of high 
employment and low inflation, 
as well as valuations that a
ppear elevated by many metrics, north korea North Korea.

"""

re.findall('North Korea\.?', txt, flags = re.I )

['North Korea', 'North Korea.', 'north korea', 'North Korea.']

In [ ]:
# Contoh Multiline

re.search('^North Korea\.?', txt, flags = re.M ) 

<_sre.SRE_Match object; span=(332, 344), match='North Korea.'>

In [ ]:
re.match('.*', txt, flags = re.DOTALL).group()

Sumber : 

[Dicoding](https://www.dicoding.com/)

[Regexr](https://regexr.com/)

[DQLab](https://dqlab.id/)

[Youtube](https://www.youtube.com/)

[Github](https://github.com/)

[NumPy](https://numpy.org/)

[Pandas](https://pandas.pydata.org/)

[Python](https://docs.python.org/)